import { Card, Button } from 'react-bootstrap';
import { motion } from 'framer-motion';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faTimes, faRobot } from '@fortawesome/free-solid-svg-icons';

const TodoSummary = ({ summary, onClose }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: -20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
    >
      <Card className="shadow-sm border-info">
        <Card.Header className="bg-info text-white d-flex justify-content-between align-items-center">
          <div>
            <FontAwesomeIcon icon={faRobot} className="me-2" />
            <strong>AI-Generated Summary</strong>
          </div>
          <Button 
            variant="link" 
            className="text-white p-0"
            onClick={onClose}
          >
            <FontAwesomeIcon icon={faTimes} />
          </Button>
        </Card.Header>
        <Card.Body>
          <Card.Text style={{ whiteSpace: 'pre-line' }}>{summary}</Card.Text>
          <div className="text-muted mt-3">
            <small>
              This summary was generated by an LLM and has been sent to your Slack channel.
            </small>
          </div>
        </Card.Body>
      </Card>
    </motion.div>
  );
};

export default TodoSummary; 